blank_issues_enabled: false
contact_links:
  - name: Question or Troubleshooting Support
    url: https://example.com
    about: If you have a question about how to use our software or need help troubleshooting a specific problem, please visit our community forum.
